./cj prog/hello.cj -o out/hello.$1
./cj prog/fn.cj -o out/fn.$1
./cj prog/matrix.cj -o out/matrix.$1
./cj prog/for.cj -o out/for.$1
./cj prog/comment.cj -o out/comment.$1
./cj prog/exp1.cj -o out/exp1.$1
./cj prog/mt.cj -o out/mt.$1
./cj prog/pid1.cj -o out/pid1.$1
./cj prog/if.cj -o out/if.$1
./cj prog/stmt1.cj -o out/stmt1.$1
./cj prog/sum.cj -o out/sum.$1
./cj prog/sum2.cj -o out/sum2.$1
./cj prog/array.cj -o out/array.$1
./cj prog/array2.cj -o out/array2.$1
